name: Build & deploy to GitHub Pages
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - name: checkout
        uses: actions/checkout@v3

      - name: install
        run: yarn install --frozen-lockfile --production

      - name: build
        run: yarn deploy
       